### PR TITLE
Fix vocabulary search using "0" as the search string

### LINKED ISSUE #1260: Vocabulary search using "0" as the query argument throws an error
## At which URL did you encounter the problem?
https://api.finto.fi/rest/v1/ykl/search

## What steps will reproduce the problem?
1. GET https://api.finto.fi/rest/v1/ykl/search?query=0

## What is the expected output? What do you see instead?
As searching by notation is a thing and 0 is a valid notation I would expect the search to work and find this item: http://urn.fi/URN:NBN:fi:au:ykl:0, just like it works with https://api.finto.fi/rest/v1/ykl/search?query=1.

Currently it throws `400 Bad Request : query parameter missing`. I'd assume this comes from php evaluating "0" to false

### PR DESCRIPTION
**Pull request by miguelvaara**
## Reasons for creating this PR

Fix the remaining cases in #1260 ; the REST API search using "0" has been fixed in #1261 and #1276, but searches for "0" in the web UI are still not working until this PR.
 
## Link to relevant issue(s), if any

- Closes #1260 

## Description of the changes in this PR

- fix ConceptSearchParameters.getSearchTerm() so it looks at the right URL parameter `q` even when its value is `"0"`
- rename the test provider method `testSearchWithZeroData` into `provideSearchWithZeroData` to avoid PHPUnit considering it a test case and complaining that it's "Risky" because it doesn't perform any assertions

## Known problems or uncertainties in this PR

n/a

## Checklist

- [x] phpUnit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if not, explain why below)
- [x] The PR doesn't introduce unintended code changes (e.g. empty lines or useless reindentation)

### CODE REVIEW

**Comment by osma** [comment]
Can you please update the PR title and description so it corresponds to current status?

**Comment by kinow** [comment]
Hadn't seen this PR, I think it's also related to the zeroes in the beginning of the search, sorry! Feel free to close mine and centralize on this one if you prefer, or use anything from that PR too :+1:

**Comment by osma** [comment]
Need to fix the conflicts caused by #1276.

**Comment by osma** [comment]
I fixed the conflicts, cleaned up the PR (removed useless test data), edited the PR title, rewrote the PR description, and tested this. I think it should be good to go now. Will wait for QA jobs, do a final check, then merge if there are no problems.

**Pull request merged**
