### PR TITLE
REST api function for retrieving all concepts present in a vocabulary  #626 

### PR DESCRIPTION
**Pull request by d0rg0ld**

### CODE REVIEW

**Comment by d0rg0ld** [comment]
Please ignore changes made to index.php, thanks

**Comment by osma** [comment]
Thanks for the PR.
Can you please remove the irrelevant parts? E.g. `.gitignore`, `index.php` and the date manipulations.

I'm worried about the approach of creating a JSON string within SPARQL. There is no escaping, so for example if a definition contains a double quote, will it break?

**Comment by d0rg0ld** [comment]
Hi, I removed the irrelevant parts. Thanks for your comment re JSON Strings from SPARQL, you are right that an unescaped double quote char would indeed break this. I had always thought that quotes must be escaped in RDF, but https://www.w3.org/TR/rdf11-concepts/#dfn-literal-value doesnt mention it - thanks for pointing this out. I suspect, however, that all RDF serializations nevertheless require it. But of course it could happen. I only tested the code with 3,6K concepts from our EnvThes thesaurus, which did not cause any problems.

**Comment by osma** [comment]
Thanks for cleaning up the PR! Now it's a lot easier to review.

The fact that RDF serializations require escaping is not relevant here, since the SPARQL endpoint always sees the literals as-is. When you perform string operations with SPARQL, you are dealing with the raw strings, not escaped ones.

I would like to see a unit test that shows that the Vocabulary.getAllConcepts() method works even in extreme cases. Skosmos is used with a lot of vocabularies and some of them have truly strange data...
For example the resource `test:ta118` in the [test.ttl](https://github.com/NatLibFi/Skosmos/blob/master/tests/test-vocab-data/test.ttl#L79) has a deliberately tricky prefLabel. Will it break your JSON serialization?

There are also a couple of SPARQL queries already in Skosmos that perform a similar trick by creating CSV strings with SPARQL string functions: [formatPropertyCsvClause](https://github.com/NatLibFi/Skosmos/blob/master/model/sparql/GenericSparql.php#L758) and [formatPrefLabelCsvClause](https://github.com/NatLibFi/Skosmos/blob/master/model/sparql/GenericSparql.php#L774). I think encoding of special characters in CSV is easier than in JSON (fewer characters to escape), so you may consider switching to CSV.

**Comment by osma** [comment]
@d0rg0ld Are you still working on this? I'm afraid that this cannot be merged in its current form as the concerns detailed above have not been addressed.

**Comment by d0rg0ld** [comment]
@osma unfortunately, I haven't had the time yet, still planning to look into this bit cant promise when this will be the case. Would it be ok to leave it open for now? Thanks

**Comment by osma** [comment]
@d0rg0ld Thanks for the update. No problem keeping it open. I hope you can find the time eventually, it would be a good feature :)

**Comment by osma** [comment]
I'm closing this for now due to inactivity. Please reopen (or open a new PR) if you still want to contribute this work.

**Pull request closed without merging**
