### PR TITLE
2 typos + a minor correction in German translation

### PR DESCRIPTION
**Pull request by hauschke**
1. 2 typos 
2. Changed msgstr "Nicht zu einem speziellen Vokabular" (line 221) a bit to make it better fitting in the German feedback form.

### CODE REVIEW

**Comment by osma** [comment]
Thanks for the PR.

However, we use Transifex to manage contributed translations, so the "master data" lives there and is just pulled to this git repository when necessary. Can you please do these changes via Transifex instead? See the [wiki page](https://github.com/NatLibFi/Skosmos/wiki/Translation) for instructions.

**Comment by hauschke** [comment]
Thanks for your pointer. I made these changes (and some others, too) at Transifex.

**Comment by osma** [comment]
This is great! The German translation has languished for quite some time. If you find any other problems, feel free to correct them on Transifex.

I pulled the updated German translations from Transifex into the `master` branch.

**Comment by hauschke** [comment]
If you could help me with a real world example of the following to statements, I could complete the translation:
https://www.transifex.com/national-library-of-finland/skosmos/translate/#de/skosmos_enpo/50899943?translated=no

**Comment by osma** [comment]
Did you look at the translator help texts in Transifex? I've added hints for most messages that have been difficult to translate, but they are not very prominent in the Transifex UI, unfortunately.

**Pull request closed without merging**
