### PR TITLE
Issue 658

### PR DESCRIPTION
**Pull request by tfrancart**
1. decode parameter before exploding it on whitespace
2. use a UNION in SPARQL query for the schemes conditions

### CODE REVIEW

**Comment by osma** [comment]
Thanks for the PR.

Would it be possible to have a unit test for the issue (#658) this is fixing?

I'd do the `$schemecond` construction a bit differently - put the individual conditions in an array, then `implode()` the array using ` UNION ` as the glue string. No need for the `substr` trickery then.

**Comment by tfrancart** [comment]
Added unit test. Used implode.

**Comment by osma** [comment]
Excellent! Waiting for Travis and other tests to complete.

**Comment by osma** [comment]
Merged after squashing into a single commit 4b131ad6873c927f1f6acb045db14319df3ea4dc

**Pull request closed without merging**
