### PR TITLE
Minor improvements found while working on another PR

### PR DESCRIPTION
**Pull request by kinow**
Hi,

A few days ago while reviewing the code for #859 , I noticed one constructor that was duplicated, then ran the static analyzer to see what else could be improved without changing important code (lower risk).

This PR contains the few ones I could put together in a few minutes :+1: 

Cheers
Bruno

### CODE REVIEW

**Comment by osma** [comment]
Thanks @kinow!

However, the [Travis builds](https://travis-ci.org/NatLibFi/Skosmos/builds/520583253) are all failing with errors like this:

```
There were 2 errors:
1) VocabularyCategoryTest::testGetVocabularies
Exception: Invalid constructor parameter given to DataObject.
/home/travis/build/NatLibFi/Skosmos/model/DataObject.php:30
/home/travis/build/NatLibFi/Skosmos/model/VocabularyCategory.php:16
/home/travis/build/NatLibFi/Skosmos/tests/VocabularyCategoryTest.php:38
2) VocabularyCategoryTest::testGetTitleWhenNoResourceGiven
Exception: Invalid constructor parameter given to DataObject.
/home/travis/build/NatLibFi/Skosmos/model/DataObject.php:30
/home/travis/build/NatLibFi/Skosmos/model/VocabularyCategory.php:16
/home/travis/build/NatLibFi/Skosmos/tests/VocabularyCategoryTest.php:57
```

**Comment by kinow** [comment]
Oh, that's an interesting one. Will try to understand what's happening and update the PR. Thanks!

**Comment by kinow** [comment]
Oh, so the constructor of `VocabularyCategory` was similar to `DataObject`'s, with a difference that I didn't notice. It doesn't check the `$resource` parameter. Dropped that commit :+1:

**Comment by osma** [comment]
Thanks! Waiting for the Travis builds to finish.

**Comment by osma** [comment]
Travis builds were succesful. Merging. Thanks a lot!

**Comment by osma** [comment]
clicked the wrong button first...

**Comment by kinow** [comment]
Thanks @osma!

**Pull request merged**
