### PR TITLE
UI language negotiation fix

### LINKED ISSUE #1453: Skosmos UI loads in Arabic
Some users are reporting that the Skosmos UI loads in Arabic by default, without having chosen that language.

Will try to investigate and gather more information.

### PR DESCRIPTION
**Pull request by namedgraph**
With these fixes applied we are not experiencing #1453 anymore.

## Reasons for creating this PR
Code fix and configuration fix

## Link to relevant issue(s), if any

- Closes #1453 

## Description of the changes in this PR
* Pass language value to `in_array()` as string instead of object
* Replaced `_` with `-` in `skosmos:languages` language tags found in the `dockerfiles` configuration files

## Checklist

- [ ] phpUnit tests pass locally with my changes
- [ ] I have added tests that show that the new code works, or tests are not relevant for this PR (e.g. only HTML/CSS changes)
- [x] The PR doesn't reduce accessibility of the front-end code (e.g. tab focus, scaling to different resolutions, use of `.sr-only` class, color contrast)
- [x] The PR doesn't introduce unintended code changes (e.g. empty lines or useless reindentation)

### CODE REVIEW

**Comment by osma** [comment]
Thanks a lot @namedgraph , this looks like a very reasonable set of fixes.

The code that this PR is targeting is really begging for unit tests. I think this would be the right moment to add those tests, verifying that the fix actually worked. I will see if I can add those easily before merging. This needs to go both to the `master` branch and to the `skosmos-3` branch where we have started to develop version 3 of Skosmos.

**Comment by osma** [comment]
I implemented unit tests for the guessLanguage method, then applied the commits from this PR on top, and put it into PR #1457 which supersedes this one.

**Comment by osma** [comment]
Merged via #1457. Thanks again!

**Comment by namedgraph** [comment]
You're welcome :)

**Pull request merged**
