### PR TITLE
Add 304 to rest controller: all of @kinow's work on PR #869

### PR DESCRIPTION
**Pull request by osma**
The original PR #869 by @kinow has been open so long that it became impossible to review. I decided to squash all the commits in it into this new PR, so that it's again possible to see what actually changes related to the current `master` branch.

Squashed commit of the following:

commit b696c80be1e7fb863995906b0d51d6ebf6075113
Merge: e821af0 c7b9c6f
Author: Osma Suominen <osma.suominen@helsinki.fi>
Date:   Wed May 6 09:21:12 2020 +0300

    Merge branch 'add-304-to-rest-controller' of https://github.com/kinow/Skosmos into kinow-add-304-to-rest-controller

commit c7b9c6f9e5da308084cec5c18aabcd7663768c67
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Sun May 19 22:21:29 2019 +1200

    Fix scrutinizer errors

commit 30baf0a953732fad4016b53fc898f272ad9f8a74
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Sun May 19 18:25:13 2019 +1200

    Updating tests for latest changes

commit 14d44369fd98bc6a469759152b01b6a8ea34f8c6
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Sun May 19 01:29:12 2019 +1200

    Move flag for enabling 304 back to VocabularyConfig, and make it available to Modifiables

commit ef1526f71d75537f041750032ee1cf5ea93d1b79
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Sun May 19 01:09:23 2019 +1200

    Use vocabulary modified date

commit 5a155443c5579ebb96cba8c649b335c0eabd32b2
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Sun May 19 00:48:39 2019 +1200

    Make Vocabulary and Concept Modifiables

commit f70a71a8d0690962f7bd4b877c8ad6c38531b086
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Thu Apr 25 00:27:26 2019 +1200

    Update tests for the new code

commit 04900fe70841aff441fc8605be3bbfca6e3db56f
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Wed Apr 24 22:07:56 2019 +1200

    Add 304 for global and concept methods

commit cd9a3fd5f5e5649a1588557e6b7afcdef87396ac
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Wed Apr 24 21:26:44 2019 +1200

    Add 304 for global and vocabulary methods

commit 9416610c063aa01416cf0917e9654b7f3c973667
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Wed Apr 24 21:08:48 2019 +1200

    Add helper method notModified in Controller class

commit 1527588c1068ae2583d1beb71e7bef337adc7c18
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Wed Apr 24 19:59:32 2019 +1200

    Simplify signature of GlobalConfiguration::getUseModifiedDate

commit e4ddf9de981c2219c3dc1ca160130b47be4784e2
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Wed Apr 24 19:41:32 2019 +1200

    Move skosmos:useModifiedDate to global configuration, instead of per vocabulary

commit e4c10ab393ae793346695169df5f7fb0e1d42a16
Author: Bruno P. Kinoshita <kinow@users.noreply.github.com>
Date:   Wed Apr 24 19:03:34 2019 +1200

    Move modified date related methods to Controller

### CODE REVIEW

**Comment by kinow** [comment]
Thank you @osma!

**Comment by kinow** [comment]
(and let me know if you need any help, please)

**Comment by osma** [comment]
FYI, I'm not sure I'm actually going to merge this PR. I just wanted to see a clean diff and results of the QA tools which also got confused about the tangled history of PR #869. I'd prefer to merge the original PR #869 if possible, but let's see.

**Comment by osma** [comment]
Some thoughts looking at the diff:

The logic for looking up the modified date of the default concept scheme is implemented twice, in [Controller.getConceptModifiedDate](https://github.com/NatLibFi/Skosmos/pull/980/files#diff-65ff53a2547dfb5ff5bf83e8f2d51228R229) and [Concept.getVocabularyModifiedDate](https://github.com/NatLibFi/Skosmos/pull/980/files#diff-b6ab98c57e17f591c74172393ba896ddR707). In contrast, [Vocabulary.getModifiedDate](https://github.com/NatLibFi/Skosmos/pull/980/files#diff-092f2a4f38449d7fdd8cb587b92e2c45R635) does not even look at the timestamp of the concept scheme - instead it looks for a timestamp for the vocabulary object which is defined in `config.ttl`, an unlikely place for a timestamp!

I think that this could be turned around: Vocabulary.getModifiedDate should look at the timestamp of the default concept scheme. Concept.getModifiedDate could fall back to `$this->getVocab()->getModifiedDate` instead of [calling getVocabularyModifiedDate](https://github.com/NatLibFi/Skosmos/pull/980/files#diff-b6ab98c57e17f591c74172393ba896ddR693) (which could be dropped).

**Comment by osma** [comment]
Second thought: test coverage could be higher, but this is mostly a consequence of not having good tests for RestController in general, so the `notModified` additions are not covered either. In any case the Concept.getVocabularyModifiedDate and Vocabulary.getModifiedDate methods should be exercised by tests (though the first one could probably be dropped - see above comment) and [according to Codecov](https://codecov.io/gh/NatLibFi/Skosmos/pull/980/diff) they are currently not.

**Comment by kinow** [comment]
All fair points @osma . Will you keep trying to merge/rebase it? Or would you prefer that I take another look at it later, and try to rebase/merge and also address your feedback?

**Comment by osma** [comment]
I think I'll try to do a proper rebase of the original PR, then do some changes (inc. above points) on top of that and ask you to review before merging. Otherwise the communication overhead just gets too large.

**Comment by kinow** [comment]
> I think I'll try to do a proper rebase of the original PR, then do some changes (inc. above points) on top of that and ask you to review before merging. Otherwise the communication overhead just gets too large. OK @kinow?

That works for me :) :+1:

**Comment by osma** [comment]
Successfully ebased the original PR. Closing this one since it's not really needed

**Pull request closed without merging**
