### PR TITLE
Multiple top concepts / dct:subject of concept schemes

### LINKED ISSUE #636: Make top ConceptSchemes in REST API an Array and not a single value
As described in  #634, the query in `GenericSparql->generateQueryConceptSchemesQuery()` makes the assumption that a concept can have at most only one `skos:topConceptOf`.
This needs to be changed if Skosmos is used to display concepts that do belong to multiple concept schemes at the same time.
Note that this will also impact the API format : "top" will hold an array and not a single value anymore.

### PR DESCRIPTION
**Pull request by tfrancart**
fix #636

### CODE REVIEW

**Comment by osma** [comment]
Thanks for the PR. Looks much cleaner than the previous one :)

**Comment by tfrancart** [comment]
Just a gentle reminder on this PR. @henriyli  were you able to review it ?
(I am asking because I have at least one other PR depending on this one to propose to handle hierarchy properly on the javascript side)
Thanks

**Comment by osma** [comment]
We reviewed this together with @henriyli and decided to merge it, looks good although we don't need this functionality in our own vocabularies

**Comment by tfrancart** [comment]
Thanks - yes, it should be harmless for data that don't use this structure.

**Pull request merged**
